# Generated by Django 2.1.8 on 2019-10-09 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField()),
                ('key', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 3, 22, 20, 48410, tzinfo=utc))),
            ],
        ),
    ]
