# Generated by Django 2.1.8 on 2019-10-09 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 5, 8, 19, 725497, tzinfo=utc)),
        ),
    ]
