# Generated by Django 2.1.8 on 2019-10-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0002_auto_20191009_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='created',
        ),
    ]
