"""
Django settings for FeiYing project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import time
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#)!%)hy*9hrgk@16k__znth4^q2mfsd2phhe-@!=b182k^927#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'diskview',
    'logview',
    'gfsview',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # must first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'FeiYing.index.LogRecodeMidware',
]

ROOT_URLCONF = 'FeiYing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'web')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FeiYing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'timeout': 20,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# log
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(levelname)s]-[%(funcName)s]-[%(asctime)s %(pathname)s %(lineno)s]: %(message)s'
        },
        'operation': {
            'format': '%(levelname)s,time:%(asctime)s,%(message)s'
            # 'format': '{"index":{"_index":"log","_type":"stsps","_id":"%(created)d%(msecs)d"}}\n%(message)s'
        }
    },
    'filters': {
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'formatter': 'standard',
            # 'filename':os.path.join('logpath', 'info-{}.log'.format(time.strftime('%Y-%m-%d')))
            'filename': '/opt/log/ldfs/ldfs_{}.log'.format(time.strftime("%m")),
            # 'maxBytes': 1024*1024*50,
            'when': 'D',
            'interval': 7,
            'backupCount': 4,
        },
        'api': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/opt/log/ldfs/api_{}.log'.format(time.strftime("%Y-%m")),
            'maxBytes': 1024*1024*50,
            'backupCount': 1,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'api': {
            'handlers': ['api'],
            'level': 'INFO',
            'propagate': False
        },
        'ldfs': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False
        },
    }
}
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/ldfs/static/'

STATIC_ROOT = 'static'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'web', 'dist'), )

DJANGO_REST_PATH = '/opt/apps/python3/lib/python3.8/site-packages/rest_framework/static/rest_framework'

CORS_ORIGIN_WHITELIST = (
        'http://127.0.0.1:8019',
        'http://localhost:8019',
    )
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_EXPOSE_HEADERS = ["Content-Disposition"]